name: Scheduled Render Job

on:
  schedule:
    # Runs every day at 3:00 AM UTC (you can change the cron pattern)
    - cron: "0 3 * * *"
  workflow_dispatch: # Add manual trigger button in GitHub UI

jobs:
  ping-render-endpoint:
    runs-on: ubuntu-latest
    env:
      CRON_KEY: ${{ secrets.CRON_KEY }}
    steps:
      - name: Call Render Cron Endpoint
        env:
          CRON_KEY: ${{ secrets.CRON_KEY }}
        run: |
          curl -X POST "https://masterclass-backend-gcne.onrender.com/cron/daily-job?key=${CRON_KEY}"
